apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
  # - basicAuth:
  #     password:
  #       name: basic-auth
  #       key: password
  #     username:
  #       name: basic-auth
  #       key: user
  #   port: web
  # namespaceSelector:
  #   matchNames:
  #   - logging
