---
apiVersion: v1
kind: Secret
metadata:
  name: loki-secrets
  namespace: kube-logging

stringData:
  # Application secrets
  # APP_KEY: "base64:ZMhMvYF89tKl6nUMwVHo6CCsPNg676OJBA2TJ2Yz7TY="

#data
  #SOME_PASSWORD: "C5&hwg5cGQMMv@2Kicb$xRY@VYrgZXKTiw3izv%6dZ@5R*&cbUS%yvzEu*svfaY$"
