apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: docker-registry-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: docker-registry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{- $auth := (printf "%s:%s" .USERNAME .PASSWORD) | toBytes | base64encode | toString -}}
          {{- $structure := (printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .HOST .USERNAME .PASSWORD $auth) -}}
          {{- print $structure -}}
  data:
  - secretKey: HOST
    remoteRef:
      key: infrastructure/artifacts/credentials
      property: host

  - secretKey: USERNAME
    remoteRef:
      key: infrastructure/artifacts/credentials
      property: username

  - secretKey: PASSWORD
    remoteRef:
      key: infrastructure/artifacts/credentials
      property: password
