apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: basic-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-global
    kind: ClusterSecretStore
  target:
    name: basic-credentials
  data:
  - secretKey: HOST
    remoteRef:
      key: infrastructure/artifacts/credentials
      property: host

  - secretKey: USERNAME
    remoteRef:
      key: infrastructure/artifacts/credentials
      property: username
