apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: automation-automata
  namespace: application-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: automation
subjects:
- kind: ServiceAccount
  name: automata
  namespace: application-a

