apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: application-a
  name: automation
rules:
- apiGroups: [""]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "watch", "list", "describe"]

