apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: replika-custom-resources
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: replika-custom-resources
subjects:
   - kind: ServiceAccount
     name: replika-controller-manager
     namespace: replika