apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: replika-custom-resources
rules:
   - apiGroups:
        - '*'
     resources:
        - '*'
     verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch