# Ref: https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml
istiod:

  global:
    istioNamespace: istio-system

    # To output all istio components logs in json format by adding --log_as_json argument to each container argument
    logAsJson: true

    proxy:
      # This controls the 'policy' in the sidecar injector.
      # Ref: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/
      autoInject: disabled

      resources:
        requests: &istioResourcesRequests
          cpu: 1000m
          memory: 1024Mi
        limits:
          <<: *istioResourcesRequests
          cpu: 2000m

  # Discovery Settings
  pilot:

    # Mesh config settings
    # Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services
    # Done this way for keeping compatibility with current Istio configuration
    ipFamilyPolicy: "SingleStack"
    ipFamilies: [ "IPv4" ]

  # Ref: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig
  meshConfig:

    # Ref: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#format-rules
    # Ref: https://www.envoyproxy.io/docs/envoy/v1.11.1/configuration/http_filters/router_filter.html?highlight=x-envoy%20attempt%20count#x-envoy-attempt-count
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: |
      {
        "protocol": "%PROTOCOL%",
        "upstream_service_time": "%REQ(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "duration": "%DURATION%",
        "request_duration": "%REQUEST_DURATION%",
        "response_duration": "%RESPONSE_DURATION%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
        "route_name": "%ROUTE_NAME%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "user_agent": "%REQ(USER-AGENT)%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "start_time": "%START_TIME%",
        "method": "%REQ(:METHOD)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "upstream_host": "%UPSTREAM_HOST%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "client_ip": "%REQ(TRUE-Client-IP)%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "authority": "%REQ(:AUTHORITY)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "response_code_details": "%RESPONSE_CODE_DETAILS%",
        "request_attempt": "%REQ(X-ENVOY-ATTEMPT-COUNT)%"
      }

    defaultConfig:
      # Configuration for the gateway topology. Used to determine the number of XFF headers that will be processed.
      gatewayTopology:
        # Number of proxies that can be chained together before reaching Istio.
        # This amount is to have an open limit.
        numTrustedProxies: 12
