# Ref: https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml
istiod:

  global:
    istioNamespace: istio-system

    logAsJson: true

    proxy:
      # This controls the 'policy' in the sidecar injector.
      # Ref: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/
      autoInject: disabled

      resources:
        requests: &istioResourcesRequests
          cpu: 500m
          memory: 512Mi
        limits: *istioResourcesRequests

  pilot:

    # Mesh config settings
    # Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services
    ipFamilyPolicy: "SingleStack"
    ipFamilies: [ "IPv4" ]

