apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reforma-custom-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reforma-custom-resources
subjects:
  - kind: ServiceAccount
    name: reforma-controller-manager